### PR TITLE
Added tests for our services

### PR DESCRIPTION
**Pull request by Nyholm**
Merge this before #62 to make sure we do not break BC

### CODE REVIEW

**Comment by rvanlaak** [comment]
Looks :+1: exept that I'm missing some newlines at the end of some files :wink:

**Comment by Nyholm** [comment]
This will also include some fixes for SF3.0 compatibility. Ref #50

**Comment by rvanlaak** [comment]
:+1: Can be merged

**Comment by Nyholm** [comment]
Thank you for the review

**Pull request merged**
