### PR TITLE
Follow symfony coding standards

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Nyholm** [comment]
Ping @rvanlaak 

Merge if you like it

**Comment by rvanlaak** [comment]
Busy on some other fixes, will add another commit to this one.

**Comment by Nyholm** [comment]
Please. Do as you want =)

**Comment by rvanlaak** [comment]
Did run some PHPStorm formatting according to the "Symfony2 code style preset", and removed the meaningless comments on the Entity getters/setters. You can merge if you like.

**Comment by Nyholm** [comment]
Awesome

**Pull request merged**
