### PR TITLE
Make sure the configuration is not as deep

### LINKED ISSUE #31: Make it easier to configure settings
There is a very deep tree. A typical setting config looks like this: 

``` yaml
dmishh_settings:
    settings:
        my_first_setting:
            scope: user
            validation:
                type: number # any Symfony2 form type
                options: # options passed to form
                    required: false
                    attr: { class: 'my-class' }
                    constraints: # To make sure the data looks like you expect
                        Symfony\Component\Validator\Constraints\Range:
                            min: 1
                            max: 65535
```

I suggest to make it a bit more flat. Maybe something like: 
``` yaml
dmishh_settings:
    settings:
        my_first_setting:
            scope: user
            type: number # any Symfony2 form type
            options: # options passed to form
                required: false
                attr: { class: 'my-class' }
            constraints: # To make sure the data looks like you expect
                Symfony\Component\Validator\Constraints\Range:
                    min: 1
                    max: 65535
```

I've moved the `type` and `constraints` up one level and removed the `validation`. How do you feel about this change? Should I make a PR?

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #31

### CODE REVIEW

**Comment by Nyholm** [comment]
@rvanlaak: If you like you are welcome to merge it.

**Comment by rvanlaak** [comment]
Given the caching docs are deleted here: https://github.com/dmishh/SettingsBundle/pull/63/files#diff-6c20d1717020c67225ab6a403345d260L72

You will add some docs about PSR-6 later?

**Comment by Nyholm** [comment]
Ive added #66 for the docs about the cache.

**Comment by rvanlaak** [comment]
Great, all tests are :+1: so will merge this.

**Pull request merged**
