### PR TITLE
Fix #76

### LINKED ISSUE #76: Error on Settings form
Hello and thx for your work these days !

I updated my project, and now I get an error when I want to display the built-in settings form : 

> `The type name specified for the service "form.type.settings_management" does not match the actual name. Expected "settings_management", given "Dmishh\SettingsBundle\Form\Type\SettingsType"`

You can quickly get rid of this error by replacing this line in `SettingsController.php` :

> `$form = $this->createForm('settings_management', $this->get('settings_manager')->all($owner));`

by that :

> `$form = $this->createForm(SettingsType::class, $this->get('settings_manager')->all($owner));`

(and add the corresponding use statement)
And then, delete the corresponding service.

Thx again for your work :+1:

### PR DESCRIPTION
**Pull request by Atyz**
Here the PR you ask to fix #76

### CODE REVIEW

**Comment by Nyholm** [comment]
If you remove the service definition you will no be able to inject the proper parameters into the form type. I believe we still need that. 

Have you read the [docs](http://symfony.com/doc/current/cookbook/form/create_custom_field_type.html#creating-your-field-type-as-a-service)?

**Comment by Atyz** [comment]
Of course.
Just going too fast without thinking...
It should be good

**Comment by Nyholm** [comment]
Awesome. Thank you. 
Would you mind squashing the commits and I would be happy to merge.

**Comment by rvanlaak** [comment]
@Atyz awesome :rocket:  Github should create a squash-commits button :+1: 

Amending the second commit + force push does the trick for me most of the times.

**Comment by Atyz** [comment]
Commits squashed :)

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
