### PR TITLE
Make sure that the twig filter is optional

### PR DESCRIPTION
**Pull request by Nyholm**
This is a nice feature to make the bundle more flexible.

### CODE REVIEW

**Comment by dmishh** [comment]
Can you explain, please, what exactly would be more flexible?

**Comment by Nyholm** [comment]
This will gives the user the possibility to not load the twig extension if you do not want it. It could be multiple reasons for that, ie you want to have your own instead or simply because you don't use it.

**Comment by dmishh** [comment]
Keeping the list of configuration options is a matter of keeping things simple. The Twig filter is quite simple and if the user wants to add his own, he's welcome to do that without doubts and conflicts with the original one.

**Comment by dmishh** [comment]
Probably, the reason of closing this one is the same as #29 
Let's keep the things as simple as possible

**Pull request closed without merging**
