### PR TITLE
Symfony 6 compatibility

### PR DESCRIPTION
**Pull request by studio-m2v**
Some changes to be compatible with Symfony 6 and PHP 8.x

### CODE REVIEW

**Comment by brzuchal** [comment]
@dmishh can we have this?

**Comment by rvanlaak** [comment]
What I am curious about is why tests do not get executed. Can you rebase on master?

**Comment by dmishh** [comment]
@brzuchal hey, I no longer maintain this repo. Richard is the one :)
btw, @rvanlaak do you want to take over this repo? I'd like to transfer it to your account since you're maintaining it like you're the owner. Maybe some listings on the packagist will need to be updated, etc

**Comment by rvanlaak** [comment]
@dmishh yes please do! 

But, maybe @FriendsOfSymfony or another group is even a better and more sustainable place?

**Comment by dmishh** [comment]
@rvanlaak I'd rather transfer to your account since you were the main contributor all the time after I stopped supporting the project. How about the packagist name or anything else required to make the transfer smooth for the users?

**Comment by rvanlaak** [comment]
Yes, please feel free to do so.

**Comment by dmishh** [comment]
@rvanlaak how about the packagist settings, etc? Should there be some changes, so it doesn't fall apart?

**Comment by rvanlaak** [comment]
Can you add me as maintainer on Packagist first? That way I can make sure to update the reference once the ownership on Github was transferred.

**Comment by dmishh** [comment]
@rvanlaak I just added you to the maintainers list - https://packagist.org/packages/dmishh/settings-bundle

**Comment by rvanlaak** [comment]
Feel free to transfer the repo @dmishh , thanks for your effort!

**Comment by dmishh** [comment]
@rvanlaak you need to delete the repo fork in your account first.
The error I'm getting during the transfer attempt: "rvanlaak/SettingsBundle already exists"

Please, do so and let me know. Thanks

**Comment by dmishh** [comment]
@rvanlaak great! "Repository transfer to rvanlaak requested"

Thanks for supporting the bundle!

**Comment by Chris53897** [comment]
Thanks @rvanlaak for takeing over the repo.
Please let us know after the transfer is completed and i hope we get symfony 6 support soon.

**Comment by rvanlaak** [comment]
@dmishh in order to not mess up possible packagist installations (as I was OoO for some days), I've not accepted the transfer yet and it now has expired. Can you resend it?

**Comment by dmishh** [comment]
@rvanlaak yep, I just initiated the transfer again

**Comment by rvanlaak** [comment]
Done! Updated the Packagist settings accordingly and left a note on README for clarity. Thank you @dmishh !

**Pull request closed without merging**
