### PR TITLE
Renamed SettingOwner to SettingsOwnerInterface

### PR DESCRIPTION
**Pull request by Nyholm**
Fixes issue #25

### CODE REVIEW

**Comment by dmishh** [comment]
After some time of thinking I suggest to pick next name for the class: `SettingsOwnerInterface` (with `s`), because owner will have many settings, it's more appropriate and logically correct than `SettingOwnerInterface` (without `s`).
And, please, check the Travis https://travis-ci.org/dmishh/SettingsBundle/jobs/56302891
Thanks!

**Comment by Nyholm** [comment]
Yeah. I agree. I've written SettingsOwner many times by misstake.

**Comment by dmishh** [comment]
Everything looks good except for phpdoc, comments have broken indentation and redundant blank lines.

**Comment by Nyholm** [comment]
I blame PHPStorm for that.. I've fixed the comments now.

**Comment by dmishh** [comment]
:+1:

**Pull request merged**
