### PR TITLE
Save only what we are told to

### PR DESCRIPTION
**Pull request by Nyholm**
**Current behavior:**
When `SettingsManager::flush()` is called, it iterates over all the settings reachable. If some setting is not stored for the owner, it creates the setting and gives it the default value. Ie, if there is 10 settings in the ALL scope and you call  `SettingsManager::flush('foobar', $owner)` we will store 10 entities in the database. 

**Suggested behavior:**
When `SettingsManager::flush()` is called, it iterates over the names in the function argument. So when we call  `SettingsManager::flush('foobar', $owner)` we will only store 1 entity. 

This will make the flush more predictable, it only flushes what we tell it to flush.

### CODE REVIEW

**Comment by dmishh** [comment]
Good change, but we definitely need a test for it

**Comment by Nyholm** [comment]
Hm, you are correct. But since `SettingsManager::flush()` is private, how can I write test code for this change without writing extra mocks for `SettingsManager::validateSetting()`, `SettingsManager::loadSettings()` and  `SettingsManager::getSettingsFromRepository()`?

Any hints would be appreciated.

**Comment by dmishh** [comment]
`flush` is a decent-size method, I prefer to test it directly using Reflection — make its visibility public for testing http://php.net/manual/en/reflectionmethod.setaccessible.php

**Comment by Nyholm** [comment]
Okey, I did not know you could do that. Thank you.

**Comment by Nyholm** [comment]
I have rebased this and added some tests

**Comment by dmishh** [comment]
:+1:

**Comment by Nyholm** [comment]
Thank you for merging.

**Pull request merged**
