### PR TITLE
Refactored documentation to separate files

### PR DESCRIPTION
**Pull request by rvanlaak**

### CODE REVIEW

**Comment by Rvanlaak** [comment]
ping @dmishh

**Comment by dmishh** [comment]
Guys, I'm alive, just ultra busy. Will try to review asap
Thanks for your help!

**Comment by Rvanlaak** [comment]
:+1: you don't have to make a new stable release after merging ;)

**Comment by Nyholm** [comment]
Great job @Rvanlaak. I like this. The Readme started to get too long. 

May I suggest a new thing to improve the PR? Since we moved all the example code once click away I suggest we should put a brief "selling" description of the bundle. Preferably before the Features. 

It could just be 2-3 sentences and a code example like: 
``` php
// set global setting
$settingsManager->set('name', 'foo');

// access user value
$settingsManager->get('name', $user); // returns 'foo'
$settingsManager->set('name', 'bar', $user); 
$settingsManager->get('name', $user); // returns 'bar'

// get global setting
$settingsManager->get('name'); // returns 'foo'

```

**Comment by Rvanlaak** [comment]
@Nyholm added some quick usage examples :+1: and also separated scope documentation into a separate file.

**Pull request merged**
